# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f36fc925e2b8261637eb3fcd81e64ba693db9ac5f12c9bed676c79f6bf7a38c47457e57a857b3adf90499887bde17bdf203da35590d1286d88622c38ab9c6e71

test:
  secret_key_base: 9896dea322bdfd57d252ba73cc8d450a1d2c9eb2e7485b547524ad70e7cf1d2d967a74108a5302a05ab08a6b57935154b1df67ef8e52ba63ec4c841f9e54d57e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
